name: Create Work Note
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy-prod:
    name: Fake deployment with review
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo deploy!

      - name: Create deployment notification
        uses: agrc/service-now-worknote-action@v1
        with:
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          system-id: ${{ secrets.SN_SYS_ID }}
